export enum EAlternativeTitleType
{
    Abbreviation = 'Abbreviation',
    Acronym = 'Acronym',
    Alternative_spelling = 'Alternative spelling',
    Alternative_title = 'Alternative title"',
    Chinese_title_simplified = 'Chinese title - simplified',
    Chinese_title_traditional = 'Chinese title - traditional',
    European_title = 'European title',
    French_title = 'French title',
    German_title = 'German title',
    Italian_title = 'Italian title',
    Japanese_title_original = 'Japanese title - original',
    Japanese_title_romanization = 'Japanese title - romanization',
    Japanese_title_stylized = 'Japanese title - stylized',
    Japanese_title_translated = 'Japanese title - translated',
    Korean_title = 'Korean title',
    Korean_title_romanization = 'Korean title romanization',
    Korean_title_translated = 'Korean title translated',
    Polish_title = 'Polish title',
    Portuguese_title = 'Portuguese title',
    Russian_title = 'Russian title',
    Spanish_title = 'Spanish title',
    Stylized_title = 'Stylized title',
    Working_title = 'Working title',
}