using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Owl.Overdrive.Domain.Entities;

namespace Owl.Overdrive.Infrastructure.Persistence.Configurations
{
    public class PlatformConfiguration : BaseEntityConfiguration, IEntityTypeConfiguration<Platform>
    {
        public PlatformConfiguration() : base()
        {

        }

        public void Configure(EntityTypeBuilder<Platform> builder)
        {
            ApplyConfiguration(builder);
            ConfigurationBase(builder);
        }

        public static void ApplyConfiguration(EntityTypeBuilder<Platform> builder)
        {
            // Table Name
            builder.ToTable("Platforms");

            // Properties parameters
            builder.Property(p => p.Name).HasColumnType("varchar(MAX)");//.HasMaxLength(255);
            builder.Property(p => p.ReleaseDate).HasColumnType("datetime2(7)");
            builder.Property(p => p.EndProduction).HasColumnType("datetime2(7)");
            builder.Property(p => p.LastGameReleased).HasColumnType("datetime2(7)");

            Seed(builder);
        }

        private static void Seed(EntityTypeBuilder<Platform> builder)
        {
            builder.HasData(new Platform() { Id = 1, Name = "1292 Advanced Programmable Video System", ReleaseDate = new DateTime(Convert.ToInt32(1976),1,1), LastGameReleased =  new DateTime(Convert.ToInt32(1983),1,1)});
            builder.HasData(new Platform() { Id = 2, Name = "3DO", ReleaseDate = new DateTime(Convert.ToInt32(1993), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1996), 1, 1) });
            builder.HasData(new Platform() { Id = 3, Name = "Acorn 32-bit", ReleaseDate = new DateTime(Convert.ToInt32(1987), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2008), 1, 1) });
            builder.HasData(new Platform() { Id = 4, Name = "Adventure Vision", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1982), 1, 1) });
            builder.HasData(new Platform() { Id = 5, Name = "AirConsole", ReleaseDate = new DateTime(Convert.ToInt32(2016), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 6, Name = "Alice 32/90", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1985), 1, 1) });
            builder.HasData(new Platform() { Id = 7, Name = "Altair 680", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1977), 1, 1) });
            builder.HasData(new Platform() { Id = 8, Name = "Altair 8800", ReleaseDate = new DateTime(Convert.ToInt32(1975), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1982), 1, 1) });
            builder.HasData(new Platform() { Id = 9, Name = "Amazon Alexa", ReleaseDate = new DateTime(Convert.ToInt32(2018), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 10, Name = "Amiga", ReleaseDate = new DateTime(Convert.ToInt32(1985), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 11, Name = "Amiga CD32", ReleaseDate = new DateTime(Convert.ToInt32(1993), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 12, Name = "Amstrad CPC", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 13, Name = "Amstrad PCW", ReleaseDate = new DateTime(Convert.ToInt32(1985), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 14, Name = "Android", ReleaseDate = new DateTime(Convert.ToInt32(2007), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 15, Name = "Antstream", ReleaseDate = new DateTime(Convert.ToInt32(2019), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 16, Name = "APF MP1000/Imagination Machine", ReleaseDate = new DateTime(Convert.ToInt32(1978), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1979), 1, 1) });
            builder.HasData(new Platform() { Id = 17, Name = "Apple I", ReleaseDate = new DateTime(Convert.ToInt32(1976), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1978), 1, 1) });
            builder.HasData(new Platform() { Id = 18, Name = "Apple II", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 19, Name = "Apple IIgs", ReleaseDate = new DateTime(Convert.ToInt32(1986), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 20, Name = "Arcade", ReleaseDate = new DateTime(Convert.ToInt32(1950), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 21, Name = "Arcadia 2001", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1983), 1, 1) });
            builder.HasData(new Platform() { Id = 22, Name = "Arduboy", ReleaseDate = new DateTime(Convert.ToInt32(2015), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2018), 1, 1) });
            builder.HasData(new Platform() { Id = 23, Name = "Astral 2000", ReleaseDate = new DateTime(Convert.ToInt32(1976), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1976), 1, 1) });
            builder.HasData(new Platform() { Id = 24, Name = "Atari 2600", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 25, Name = "Atari 5200", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 26, Name = "Atari 7800", ReleaseDate = new DateTime(Convert.ToInt32(1986), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 27, Name = "Atari 8-bit", ReleaseDate = new DateTime(Convert.ToInt32(1979), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 28, Name = "Atari ST", ReleaseDate = new DateTime(Convert.ToInt32(1985), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 29, Name = "Atom", ReleaseDate = new DateTime(Convert.ToInt32(1980), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 30, Name = "bada", ReleaseDate = new DateTime(Convert.ToInt32(2010), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2014), 1, 1) });
            builder.HasData(new Platform() { Id = 31, Name = "Bally Astrocade", ReleaseDate = new DateTime(Convert.ToInt32(1978), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1983), 1, 1) });
            builder.HasData(new Platform() { Id = 32, Name = "BBC Micro", ReleaseDate = new DateTime(Convert.ToInt32(1981), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 33, Name = "BeOS", ReleaseDate = new DateTime(Convert.ToInt32(1997), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2011), 1, 1) });
            builder.HasData(new Platform() { Id = 34, Name = "BlackBerry", ReleaseDate = new DateTime(Convert.ToInt32(2007), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2017), 1, 1) });
            builder.HasData(new Platform() { Id = 35, Name = "Blacknut", ReleaseDate = new DateTime(Convert.ToInt32(2018), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 36, Name = "Blu-ray Disc Player", ReleaseDate = new DateTime(Convert.ToInt32(2007), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2016), 1, 1) });
            builder.HasData(new Platform() { Id = 37, Name = "BREW", ReleaseDate = new DateTime(Convert.ToInt32(2002), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2012), 1, 1) });
            builder.HasData(new Platform() { Id = 38, Name = "Browser", ReleaseDate = new DateTime(Convert.ToInt32(1994), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 39, Name = "Bubble", ReleaseDate = new DateTime(Convert.ToInt32(2005), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2005), 1, 1) });
            builder.HasData(new Platform() { Id = 40, Name = "Camputers Lynx", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1984), 1, 1) });
            builder.HasData(new Platform() { Id = 41, Name = "Casio Loopy", ReleaseDate = new DateTime(Convert.ToInt32(1995), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1996), 1, 1) });
            builder.HasData(new Platform() { Id = 42, Name = "Casio Programmable Calculator", ReleaseDate = new DateTime(Convert.ToInt32(1978), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1978), 1, 1) });
            builder.HasData(new Platform() { Id = 43, Name = "Casio PV-1000", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 44, Name = "CD-i", ReleaseDate = new DateTime(Convert.ToInt32(1990), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 45, Name = "CDTV", ReleaseDate = new DateTime(Convert.ToInt32(1991), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1993), 1, 1) });
            builder.HasData(new Platform() { Id = 46, Name = "Champion 2711", ReleaseDate = new DateTime(Convert.ToInt32(1978), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1978), 1, 1) });
            builder.HasData(new Platform() { Id = 47, Name = "Channel F", ReleaseDate = new DateTime(Convert.ToInt32(1976), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2009), 1, 1) });
            builder.HasData(new Platform() { Id = 48, Name = "ClickStart", ReleaseDate = new DateTime(Convert.ToInt32(2007), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2008), 1, 1) });
            builder.HasData(new Platform() { Id = 49, Name = "Coleco Adam", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2017), 1, 1) });
            builder.HasData(new Platform() { Id = 50, Name = "ColecoVision", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 51, Name = "Colour Genie", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1984), 1, 1) });
            builder.HasData(new Platform() { Id = 52, Name = "Commodore 128", ReleaseDate = new DateTime(Convert.ToInt32(1985), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 53, Name = "Commodore 16, Plus/4", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 54, Name = "Commodore 64", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 55, Name = "Commodore PET/CBM", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 56, Name = "Compal 80", ReleaseDate = new DateTime(Convert.ToInt32(1978), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1978), 1, 1) });
            builder.HasData(new Platform() { Id = 57, Name = "Compucolor I", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1978), 1, 1) });
            builder.HasData(new Platform() { Id = 58, Name = "Compucolor II", ReleaseDate = new DateTime(Convert.ToInt32(1978), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1980), 1, 1) });
            builder.HasData(new Platform() { Id = 59, Name = "Compucorp Programmable Calculator", ReleaseDate = new DateTime(Convert.ToInt32(1975), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1976), 1, 1) });
            builder.HasData(new Platform() { Id = 60, Name = "COSMAC", ReleaseDate = new DateTime(Convert.ToInt32(1976), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1981), 1, 1) });
            builder.HasData(new Platform() { Id = 61, Name = "CP/M", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 62, Name = "CreatiVision", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1982), 1, 1) });
            builder.HasData(new Platform() { Id = 63, Name = "Cybervision", ReleaseDate = new DateTime(Convert.ToInt32(1978), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1979), 1, 1) });
            builder.HasData(new Platform() { Id = 64, Name = "Danger OS", ReleaseDate = new DateTime(Convert.ToInt32(2007), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2007), 1, 1) });
            builder.HasData(new Platform() { Id = 65, Name = "Dedicated console", ReleaseDate = new DateTime(Convert.ToInt32(1956), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 66, Name = "Dedicated handheld", ReleaseDate = new DateTime(Convert.ToInt32(1976), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 67, Name = "Didj", ReleaseDate = new DateTime(Convert.ToInt32(2008), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2008), 1, 1) });
            builder.HasData(new Platform() { Id = 68, Name = "digiBlast", ReleaseDate = new DateTime(Convert.ToInt32(2005), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2007), 1, 1) });
            builder.HasData(new Platform() { Id = 69, Name = "DoJa", ReleaseDate = new DateTime(Convert.ToInt32(2001), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2012), 1, 1) });
            builder.HasData(new Platform() { Id = 70, Name = "DOS", ReleaseDate = new DateTime(Convert.ToInt32(1981), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 71, Name = "Dragon 32/64", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 72, Name = "Dreamcast", ReleaseDate = new DateTime(Convert.ToInt32(1998), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 73, Name = "DVD Player", ReleaseDate = new DateTime(Convert.ToInt32(1997), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 74, Name = "ECD Micromind", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1977), 1, 1) });
            builder.HasData(new Platform() { Id = 75, Name = "Electron", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 76, Name = "Enterprise", ReleaseDate = new DateTime(Convert.ToInt32(1985), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2018), 1, 1) });
            builder.HasData(new Platform() { Id = 77, Name = "Epoch Cassette Vision", ReleaseDate = new DateTime(Convert.ToInt32(1981), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1981), 1, 1) });
            builder.HasData(new Platform() { Id = 78, Name = "Epoch Game Pocket Computer", ReleaseDate = new DateTime(Convert.ToInt32(1985), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 79, Name = "Epoch Super Cassette Vision", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1986), 1, 1) });
            builder.HasData(new Platform() { Id = 80, Name = "Evercade", ReleaseDate = new DateTime(Convert.ToInt32(2020), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 81, Name = "Exelvision", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1986), 1, 1) });
            builder.HasData(new Platform() { Id = 82, Name = "ExEn", ReleaseDate = new DateTime(Convert.ToInt32(2001), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2006), 1, 1) });
            builder.HasData(new Platform() { Id = 83, Name = "Exidy Sorcerer", ReleaseDate = new DateTime(Convert.ToInt32(1978), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1985), 1, 1) });
            builder.HasData(new Platform() { Id = 84, Name = "Fire OS", ReleaseDate = new DateTime(Convert.ToInt32(2011), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 85, Name = "FM Towns", ReleaseDate = new DateTime(Convert.ToInt32(1989), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 86, Name = "FM-7", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 87, Name = "Freebox", ReleaseDate = new DateTime(Convert.ToInt32(2011), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2018), 1, 1) });
            builder.HasData(new Platform() { Id = 88, Name = "G-cluster", ReleaseDate = new DateTime(Convert.ToInt32(2016), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 89, Name = "Galaksija", ReleaseDate = new DateTime(Convert.ToInt32(1985), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1988), 1, 1) });
            builder.HasData(new Platform() { Id = 90, Name = "Game Boy", ReleaseDate = new DateTime(Convert.ToInt32(1989), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 91, Name = "Game Boy Advance", ReleaseDate = new DateTime(Convert.ToInt32(2001), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 92, Name = "Game Boy Color", ReleaseDate = new DateTime(Convert.ToInt32(1998), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 93, Name = "Game Gear", ReleaseDate = new DateTime(Convert.ToInt32(1990), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 94, Name = "Game Wave", ReleaseDate = new DateTime(Convert.ToInt32(2005), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2010), 1, 1) });
            builder.HasData(new Platform() { Id = 95, Name = "Game.Com", ReleaseDate = new DateTime(Convert.ToInt32(1997), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1999), 1, 1) });
            builder.HasData(new Platform() { Id = 96, Name = "GameCube", ReleaseDate = new DateTime(Convert.ToInt32(2001), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2015), 1, 1) });
            builder.HasData(new Platform() { Id = 97, Name = "GameStick", ReleaseDate = new DateTime(Convert.ToInt32(2013), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2015), 1, 1) });
            builder.HasData(new Platform() { Id = 98, Name = "Genesis", ReleaseDate = new DateTime(Convert.ToInt32(1988), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 99, Name = "GIMINI", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1982), 1, 1) });
            builder.HasData(new Platform() { Id = 100, Name = "Gizmondo", ReleaseDate = new DateTime(Convert.ToInt32(2004), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2005), 1, 1) });
            builder.HasData(new Platform() { Id = 101, Name = "Gloud", ReleaseDate = new DateTime(Convert.ToInt32(2017), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2019), 1, 1) });
            builder.HasData(new Platform() { Id = 102, Name = "Glulx", ReleaseDate = new DateTime(Convert.ToInt32(2011), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2017), 1, 1) });
            builder.HasData(new Platform() { Id = 103, Name = "GNEX", ReleaseDate = new DateTime(Convert.ToInt32(2004), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2005), 1, 1) });
            builder.HasData(new Platform() { Id = 104, Name = "GP2X", ReleaseDate = new DateTime(Convert.ToInt32(2005), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2014), 1, 1) });
            builder.HasData(new Platform() { Id = 105, Name = "GP2X Wiz", ReleaseDate = new DateTime(Convert.ToInt32(2009), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2015), 1, 1) });
            builder.HasData(new Platform() { Id = 106, Name = "GP32", ReleaseDate = new DateTime(Convert.ToInt32(2001), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2010), 1, 1) });
            builder.HasData(new Platform() { Id = 107, Name = "GVM", ReleaseDate = new DateTime(Convert.ToInt32(2003), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2005), 1, 1) });
            builder.HasData(new Platform() { Id = 108, Name = "HD DVD Player", ReleaseDate = new DateTime(Convert.ToInt32(2007), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2007), 1, 1) });
            builder.HasData(new Platform() { Id = 109, Name = "Heath/Zenith H8/H89", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1982), 1, 1) });
            builder.HasData(new Platform() { Id = 110, Name = "Heathkit H11", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1983), 1, 1) });
            builder.HasData(new Platform() { Id = 111, Name = "Hitachi S1", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 112, Name = "HP 9800", ReleaseDate = new DateTime(Convert.ToInt32(1974), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1976), 1, 1) });
            builder.HasData(new Platform() { Id = 113, Name = "HP Programmable Calculator", ReleaseDate = new DateTime(Convert.ToInt32(1975), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2011), 1, 1) });
            builder.HasData(new Platform() { Id = 114, Name = "Hugo", ReleaseDate = new DateTime(Convert.ToInt32(2011), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2011), 1, 1) });
            builder.HasData(new Platform() { Id = 115, Name = "HyperScan", ReleaseDate = new DateTime(Convert.ToInt32(2006), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2007), 1, 1) });
            builder.HasData(new Platform() { Id = 116, Name = "IBM 5100", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1977), 1, 1) });
            builder.HasData(new Platform() { Id = 117, Name = "Ideal-Computer", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1978), 1, 1) });
            builder.HasData(new Platform() { Id = 118, Name = "iiRcade", ReleaseDate = new DateTime(Convert.ToInt32(2021), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 119, Name = "Intel 8008", ReleaseDate = new DateTime(Convert.ToInt32(1975), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1976), 1, 1) });
            builder.HasData(new Platform() { Id = 120, Name = "Intel 8080", ReleaseDate = new DateTime(Convert.ToInt32(1975), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1979), 1, 1) });
            builder.HasData(new Platform() { Id = 121, Name = "Intellivision", ReleaseDate = new DateTime(Convert.ToInt32(1979), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 122, Name = "Interact Model One", ReleaseDate = new DateTime(Convert.ToInt32(1978), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1978), 1, 1) });
            builder.HasData(new Platform() { Id = 123, Name = "Interton Video 2000", ReleaseDate = new DateTime(Convert.ToInt32(1975), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1976), 1, 1) });
            builder.HasData(new Platform() { Id = 124, Name = "iPad", ReleaseDate = new DateTime(Convert.ToInt32(2009), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 125, Name = "iPhone", ReleaseDate = new DateTime(Convert.ToInt32(2008), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 126, Name = "iPod Classic", ReleaseDate = new DateTime(Convert.ToInt32(2004), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2009), 1, 1) });
            builder.HasData(new Platform() { Id = 127, Name = "J2ME", ReleaseDate = new DateTime(Convert.ToInt32(2000), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2018), 1, 1) });
            builder.HasData(new Platform() { Id = 128, Name = "Jaguar", ReleaseDate = new DateTime(Convert.ToInt32(1993), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 129, Name = "Jolt", ReleaseDate = new DateTime(Convert.ToInt32(1976), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1977), 1, 1) });
            builder.HasData(new Platform() { Id = 130, Name = "Jupiter Ace", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2009), 1, 1) });
            builder.HasData(new Platform() { Id = 131, Name = "KaiOS", ReleaseDate = null, LastGameReleased = null });
            builder.HasData(new Platform() { Id = 132, Name = "KIM-1", ReleaseDate = new DateTime(Convert.ToInt32(1976), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1979), 1, 1) });
            builder.HasData(new Platform() { Id = 133, Name = "Kindle Classic", ReleaseDate = new DateTime(Convert.ToInt32(2010), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2013), 1, 1) });
            builder.HasData(new Platform() { Id = 134, Name = "Laser 200", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 135, Name = "LaserActive", ReleaseDate = new DateTime(Convert.ToInt32(1993), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1996), 1, 1) });
            builder.HasData(new Platform() { Id = 136, Name = "LeapFrog Explorer", ReleaseDate = new DateTime(Convert.ToInt32(2010), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2012), 1, 1) });
            builder.HasData(new Platform() { Id = 137, Name = "Leapster", ReleaseDate = new DateTime(Convert.ToInt32(2003), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2011), 1, 1) });
            builder.HasData(new Platform() { Id = 138, Name = "LeapTV", ReleaseDate = new DateTime(Convert.ToInt32(2014), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2014), 1, 1) });
            builder.HasData(new Platform() { Id = 139, Name = "Linux", ReleaseDate = new DateTime(Convert.ToInt32(1991), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 140, Name = "Luna", ReleaseDate = new DateTime(Convert.ToInt32(2020), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 141, Name = "Lynx", ReleaseDate = new DateTime(Convert.ToInt32(1989), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 142, Name = "Macintosh", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 143, Name = "Maemo", ReleaseDate = new DateTime(Convert.ToInt32(2008), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2012), 1, 1) });
            builder.HasData(new Platform() { Id = 144, Name = "Mainframe", ReleaseDate = new DateTime(Convert.ToInt32(1948), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1994), 1, 1) });
            builder.HasData(new Platform() { Id = 145, Name = "Matsushita/Panasonic JR", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 146, Name = "Mattel Aquarius", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 147, Name = "MeeGo", ReleaseDate = new DateTime(Convert.ToInt32(2011), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2012), 1, 1) });
            builder.HasData(new Platform() { Id = 148, Name = "Memotech MTX", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1985), 1, 1) });
            builder.HasData(new Platform() { Id = 149, Name = "Meritum", ReleaseDate = new DateTime(Convert.ToInt32(1985), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1987), 1, 1) });
            builder.HasData(new Platform() { Id = 150, Name = "Microbee", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2014), 1, 1) });
            builder.HasData(new Platform() { Id = 151, Name = "Microtan 65", ReleaseDate = new DateTime(Convert.ToInt32(1980), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1980), 1, 1) });
            builder.HasData(new Platform() { Id = 152, Name = "Microvision", ReleaseDate = new DateTime(Convert.ToInt32(1979), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1982), 1, 1) });
            builder.HasData(new Platform() { Id = 153, Name = "Mophun", ReleaseDate = new DateTime(Convert.ToInt32(2002), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2005), 1, 1) });
            builder.HasData(new Platform() { Id = 154, Name = "MOS Technology 6502", ReleaseDate = new DateTime(Convert.ToInt32(1976), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1981), 1, 1) });
            builder.HasData(new Platform() { Id = 155, Name = "Motorola 6800", ReleaseDate = new DateTime(Convert.ToInt32(1976), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1981), 1, 1) });
            builder.HasData(new Platform() { Id = 156, Name = "Motorola 68k", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1986), 1, 1) });
            builder.HasData(new Platform() { Id = 157, Name = "MRE", ReleaseDate = new DateTime(Convert.ToInt32(2012), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2017), 1, 1) });
            builder.HasData(new Platform() { Id = 158, Name = "MSX", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 159, Name = "N-Gage", ReleaseDate = new DateTime(Convert.ToInt32(2003), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 160, Name = "N-Gage (service)", ReleaseDate = new DateTime(Convert.ToInt32(2008), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2009), 1, 1) });
            builder.HasData(new Platform() { Id = 161, Name = "Nascom", ReleaseDate = new DateTime(Convert.ToInt32(1979), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1984), 1, 1) });
            builder.HasData(new Platform() { Id = 162, Name = "Neo Geo", ReleaseDate = new DateTime(Convert.ToInt32(1991), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 163, Name = "Neo Geo CD", ReleaseDate = new DateTime(Convert.ToInt32(1994), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 164, Name = "Neo Geo Pocket", ReleaseDate = new DateTime(Convert.ToInt32(1998), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1998), 1, 1) });
            builder.HasData(new Platform() { Id = 165, Name = "Neo Geo Pocket Color", ReleaseDate = new DateTime(Convert.ToInt32(1999), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2001), 1, 1) });
            builder.HasData(new Platform() { Id = 166, Name = "Neo Geo X", ReleaseDate = new DateTime(Convert.ToInt32(2012), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2013), 1, 1) });
            builder.HasData(new Platform() { Id = 167, Name = "NES", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 168, Name = "New Nintendo 3DS", ReleaseDate = new DateTime(Convert.ToInt32(2015), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 169, Name = "NewBrain", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1983), 1, 1) });
            builder.HasData(new Platform() { Id = 170, Name = "Newton", ReleaseDate = new DateTime(Convert.ToInt32(1993), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2002), 1, 1) });
            builder.HasData(new Platform() { Id = 171, Name = "Nintendo 3DS", ReleaseDate = new DateTime(Convert.ToInt32(2011), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 172, Name = "Nintendo 64", ReleaseDate = new DateTime(Convert.ToInt32(1996), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2019), 1, 1) });
            builder.HasData(new Platform() { Id = 173, Name = "Nintendo DS", ReleaseDate = new DateTime(Convert.ToInt32(2004), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 174, Name = "Nintendo DSi", ReleaseDate = new DateTime(Convert.ToInt32(2008), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2016), 1, 1) });
            builder.HasData(new Platform() { Id = 175, Name = "Nintendo Switch", ReleaseDate = new DateTime(Convert.ToInt32(2017), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 176, Name = "North Star", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1983), 1, 1) });
            builder.HasData(new Platform() { Id = 177, Name = "Noval 760", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1977), 1, 1) });
            builder.HasData(new Platform() { Id = 178, Name = "Nuon", ReleaseDate = new DateTime(Convert.ToInt32(2000), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2001), 1, 1) });
            builder.HasData(new Platform() { Id = 179, Name = "Oculus Go", ReleaseDate = new DateTime(Convert.ToInt32(2015), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 180, Name = "Oculus Quest", ReleaseDate = new DateTime(Convert.ToInt32(2019), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 181, Name = "Odyssey", ReleaseDate = new DateTime(Convert.ToInt32(1972), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1973), 1, 1) });
            builder.HasData(new Platform() { Id = 182, Name = "Odyssey 2", ReleaseDate = new DateTime(Convert.ToInt32(1978), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2017), 1, 1) });
            builder.HasData(new Platform() { Id = 183, Name = "Ohio Scientific", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1982), 1, 1) });
            builder.HasData(new Platform() { Id = 184, Name = "OnLive", ReleaseDate = new DateTime(Convert.ToInt32(2010), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2014), 1, 1) });
            builder.HasData(new Platform() { Id = 185, Name = "OOParts", ReleaseDate = new DateTime(Convert.ToInt32(2020), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 186, Name = "Orao", ReleaseDate = new DateTime(Convert.ToInt32(1985), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1986), 1, 1) });
            builder.HasData(new Platform() { Id = 187, Name = "Oric", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 188, Name = "OS/2", ReleaseDate = new DateTime(Convert.ToInt32(1988), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2015), 1, 1) });
            builder.HasData(new Platform() { Id = 189, Name = "Ouya", ReleaseDate = new DateTime(Convert.ToInt32(2013), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 190, Name = "Palm OS", ReleaseDate = new DateTime(Convert.ToInt32(1998), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2010), 1, 1) });
            builder.HasData(new Platform() { Id = 191, Name = "Pandora", ReleaseDate = null, LastGameReleased = null });
            builder.HasData(new Platform() { Id = 192, Name = "PC Booter", ReleaseDate = new DateTime(Convert.ToInt32(1981), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2016), 1, 1) });
            builder.HasData(new Platform() { Id = 193, Name = "PC-6001", ReleaseDate = new DateTime(Convert.ToInt32(1981), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 194, Name = "PC-8000", ReleaseDate = new DateTime(Convert.ToInt32(1981), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 195, Name = "PC-88", ReleaseDate = new DateTime(Convert.ToInt32(1981), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 196, Name = "PC-98", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 197, Name = "PC-FX", ReleaseDate = new DateTime(Convert.ToInt32(1994), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1998), 1, 1) });
            builder.HasData(new Platform() { Id = 198, Name = "Pebble", ReleaseDate = new DateTime(Convert.ToInt32(2016), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2016), 1, 1) });
            builder.HasData(new Platform() { Id = 199, Name = "Philips VG 5000", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2013), 1, 1) });
            builder.HasData(new Platform() { Id = 200, Name = "Photo CD", ReleaseDate = new DateTime(Convert.ToInt32(1995), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1995), 1, 1) });
            builder.HasData(new Platform() { Id = 201, Name = "Pippin", ReleaseDate = new DateTime(Convert.ToInt32(1995), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1997), 1, 1) });
            builder.HasData(new Platform() { Id = 202, Name = "Playdate", ReleaseDate = new DateTime(Convert.ToInt32(2021), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 203, Name = "Playdia", ReleaseDate = new DateTime(Convert.ToInt32(1994), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1994), 1, 1) });
            builder.HasData(new Platform() { Id = 204, Name = "PlayStation", ReleaseDate = new DateTime(Convert.ToInt32(1994), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 205, Name = "PlayStation 2", ReleaseDate = new DateTime(Convert.ToInt32(2000), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2015), 1, 1) });
            builder.HasData(new Platform() { Id = 206, Name = "PlayStation 3", ReleaseDate = new DateTime(Convert.ToInt32(2006), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 207, Name = "PlayStation 4", ReleaseDate = new DateTime(Convert.ToInt32(2013), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 208, Name = "PlayStation 5", ReleaseDate = new DateTime(Convert.ToInt32(2020), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 209, Name = "PlayStation Now", ReleaseDate = new DateTime(Convert.ToInt32(2014), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 210, Name = "Plex Arcade", ReleaseDate = new DateTime(Convert.ToInt32(2021), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 211, Name = "Pokitto", ReleaseDate = new DateTime(Convert.ToInt32(2017), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2017), 1, 1) });
            builder.HasData(new Platform() { Id = 212, Name = "Pokémon Mini", ReleaseDate = new DateTime(Convert.ToInt32(2001), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2002), 1, 1) });
            builder.HasData(new Platform() { Id = 213, Name = "Poly-88", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1979), 1, 1) });
            builder.HasData(new Platform() { Id = 214, Name = "PS Vita", ReleaseDate = new DateTime(Convert.ToInt32(2011), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 215, Name = "PSP", ReleaseDate = new DateTime(Convert.ToInt32(2004), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 216, Name = "RCA Studio II", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1978), 1, 1) });
            builder.HasData(new Platform() { Id = 217, Name = "Research Machines 380Z", ReleaseDate = new DateTime(Convert.ToInt32(1979), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1979), 1, 1) });
            builder.HasData(new Platform() { Id = 218, Name = "Roku", ReleaseDate = new DateTime(Convert.ToInt32(2011), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 219, Name = "SAM Coupé", ReleaseDate = new DateTime(Convert.ToInt32(1990), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2018), 1, 1) });
            builder.HasData(new Platform() { Id = 220, Name = "SC/MP", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1979), 1, 1) });
            builder.HasData(new Platform() { Id = 221, Name = "SD-200/270/290", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1983), 1, 1) });
            builder.HasData(new Platform() { Id = 222, Name = "SEGA 32X", ReleaseDate = new DateTime(Convert.ToInt32(1994), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1996), 1, 1) });
            builder.HasData(new Platform() { Id = 223, Name = "SEGA CD", ReleaseDate = new DateTime(Convert.ToInt32(1991), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2016), 1, 1) });
            builder.HasData(new Platform() { Id = 224, Name = "SEGA Master System", ReleaseDate = new DateTime(Convert.ToInt32(1985), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 225, Name = "SEGA Pico", ReleaseDate = new DateTime(Convert.ToInt32(1994), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2004), 1, 1) });
            builder.HasData(new Platform() { Id = 226, Name = "SEGA Saturn", ReleaseDate = new DateTime(Convert.ToInt32(1994), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2000), 1, 1) });
            builder.HasData(new Platform() { Id = 227, Name = "SG-1000", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 228, Name = "Sharp MZ-80B/2000/2500", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 229, Name = "Sharp MZ-80K/700/800/1500", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 230, Name = "Sharp X1", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 231, Name = "Sharp X68000", ReleaseDate = new DateTime(Convert.ToInt32(1987), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 232, Name = "Sharp Zaurus", ReleaseDate = new DateTime(Convert.ToInt32(2000), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2002), 1, 1) });
            builder.HasData(new Platform() { Id = 233, Name = "Signetics 2650", ReleaseDate = new DateTime(Convert.ToInt32(1978), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1978), 1, 1) });
            builder.HasData(new Platform() { Id = 234, Name = "Sinclair QL", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2016), 1, 1) });
            builder.HasData(new Platform() { Id = 235, Name = "SK-VM", ReleaseDate = new DateTime(Convert.ToInt32(2004), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2007), 1, 1) });
            builder.HasData(new Platform() { Id = 236, Name = "SMC-777", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 237, Name = "SNES", ReleaseDate = new DateTime(Convert.ToInt32(1990), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 238, Name = "Socrates	", ReleaseDate = null, LastGameReleased = null });
            builder.HasData(new Platform() { Id = 239, Name = "Sol-20", ReleaseDate = new DateTime(Convert.ToInt32(1976), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2003), 1, 1) });
            builder.HasData(new Platform() { Id = 240, Name = "Sord M5", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 241, Name = "Spectravideo", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1987), 1, 1) });
            builder.HasData(new Platform() { Id = 242, Name = "SRI-500/1000", ReleaseDate = new DateTime(Convert.ToInt32(1976), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1976), 1, 1) });
            builder.HasData(new Platform() { Id = 243, Name = "Stadia", ReleaseDate = new DateTime(Convert.ToInt32(2019), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 244, Name = "Super A'can", ReleaseDate = new DateTime(Convert.ToInt32(1995), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1996), 1, 1) });
            builder.HasData(new Platform() { Id = 245, Name = "Super Vision 8000", ReleaseDate = new DateTime(Convert.ToInt32(1978), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1979), 1, 1) });
            builder.HasData(new Platform() { Id = 246, Name = "SuperGrafx", ReleaseDate = new DateTime(Convert.ToInt32(1989), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1991), 1, 1) });
            builder.HasData(new Platform() { Id = 247, Name = "Supervision", ReleaseDate = new DateTime(Convert.ToInt32(1992), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2019), 1, 1) });
            builder.HasData(new Platform() { Id = 248, Name = "Sure Shot HD", ReleaseDate = new DateTime(Convert.ToInt32(2016), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2017), 1, 1) });
            builder.HasData(new Platform() { Id = 249, Name = "SWTPC 6800", ReleaseDate = new DateTime(Convert.ToInt32(1976), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2018), 1, 1) });
            builder.HasData(new Platform() { Id = 250, Name = "Symbian", ReleaseDate = new DateTime(Convert.ToInt32(1998), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 251, Name = "TADS", ReleaseDate = new DateTime(Convert.ToInt32(1994), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2019), 1, 1) });
            builder.HasData(new Platform() { Id = 252, Name = "Taito X-55", ReleaseDate = new DateTime(Convert.ToInt32(1995), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1995), 1, 1) });
            builder.HasData(new Platform() { Id = 253, Name = "Tatung Einstein", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1989), 1, 1) });
            builder.HasData(new Platform() { Id = 254, Name = "Tektronix 4050", ReleaseDate = new DateTime(Convert.ToInt32(1975), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1977), 1, 1) });
            builder.HasData(new Platform() { Id = 255, Name = "Tele-Spiel ES-2201", ReleaseDate = new DateTime(Convert.ToInt32(1975), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1975), 1, 1) });
            builder.HasData(new Platform() { Id = 256, Name = "Telstar Arcade", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1977), 1, 1) });
            builder.HasData(new Platform() { Id = 257, Name = "Terminal", ReleaseDate = new DateTime(Convert.ToInt32(1969), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2002), 1, 1) });
            builder.HasData(new Platform() { Id = 258, Name = "Thomson MO", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1989), 1, 1) });
            builder.HasData(new Platform() { Id = 259, Name = "Thomson TO", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2018), 1, 1) });
            builder.HasData(new Platform() { Id = 260, Name = "TI Programmable Calculator", ReleaseDate = new DateTime(Convert.ToInt32(1976), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 261, Name = "TI-99/4A", ReleaseDate = new DateTime(Convert.ToInt32(1979), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 262, Name = "Tiki 100", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1986), 1, 1) });
            builder.HasData(new Platform() { Id = 263, Name = "TIM", ReleaseDate = new DateTime(Convert.ToInt32(1976), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1977), 1, 1) });
            builder.HasData(new Platform() { Id = 264, Name = "Timex Sinclair 2068", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2013), 1, 1) });
            builder.HasData(new Platform() { Id = 265, Name = "Tizen", ReleaseDate = new DateTime(Convert.ToInt32(2015), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2017), 1, 1) });
            builder.HasData(new Platform() { Id = 266, Name = "Tomahawk F1", ReleaseDate = new DateTime(Convert.ToInt32(2016), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2016), 1, 1) });
            builder.HasData(new Platform() { Id = 267, Name = "Tomy Tutor", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 268, Name = "Triton", ReleaseDate = new DateTime(Convert.ToInt32(1978), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1979), 1, 1) });
            builder.HasData(new Platform() { Id = 269, Name = "TRS-80", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 270, Name = "TRS-80 CoCo", ReleaseDate = new DateTime(Convert.ToInt32(1980), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 271, Name = "TRS-80 MC-10", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 272, Name = "TRS-80 Model 100", ReleaseDate = new DateTime(Convert.ToInt32(1984), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1984), 1, 1) });
            builder.HasData(new Platform() { Id = 273, Name = "TurboGrafx CD", ReleaseDate = new DateTime(Convert.ToInt32(1988), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2018), 1, 1) });
            builder.HasData(new Platform() { Id = 274, Name = "TurboGrafx-16", ReleaseDate = new DateTime(Convert.ToInt32(1987), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 275, Name = "tvOS", ReleaseDate = new DateTime(Convert.ToInt32(2015), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 276, Name = "V.Flash", ReleaseDate = new DateTime(Convert.ToInt32(2006), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2007), 1, 1) });
            builder.HasData(new Platform() { Id = 277, Name = "V.Smile", ReleaseDate = new DateTime(Convert.ToInt32(2004), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2009), 1, 1) });
            builder.HasData(new Platform() { Id = 278, Name = "Vectrex", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 279, Name = "Versatile", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1978), 1, 1) });
            builder.HasData(new Platform() { Id = 280, Name = "VIC-20", ReleaseDate = new DateTime(Convert.ToInt32(1980), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 281, Name = "VideoBrain", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1978), 1, 1) });
            builder.HasData(new Platform() { Id = 282, Name = "Videopac+ G7400", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2014), 1, 1) });
            builder.HasData(new Platform() { Id = 283, Name = "Virtual Boy", ReleaseDate = new DateTime(Convert.ToInt32(1995), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2003), 1, 1) });
            builder.HasData(new Platform() { Id = 284, Name = "VIS", ReleaseDate = new DateTime(Convert.ToInt32(1992), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1992), 1, 1) });
            builder.HasData(new Platform() { Id = 285, Name = "Wang 2200", ReleaseDate = new DateTime(Convert.ToInt32(1974), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1981), 1, 1) });
            builder.HasData(new Platform() { Id = 286, Name = "watchOS", ReleaseDate = new DateTime(Convert.ToInt32(2015), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 287, Name = "webOS", ReleaseDate = new DateTime(Convert.ToInt32(2009), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2021), 1, 1) });
            builder.HasData(new Platform() { Id = 288, Name = "Wii", ReleaseDate = new DateTime(Convert.ToInt32(2006), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 289, Name = "Wii U", ReleaseDate = new DateTime(Convert.ToInt32(2012), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 290, Name = "Windows", ReleaseDate = new DateTime(Convert.ToInt32(1993), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 291, Name = "Windows 3.x", ReleaseDate = new DateTime(Convert.ToInt32(1988), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 292, Name = "Windows Apps", ReleaseDate = new DateTime(Convert.ToInt32(2012), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 293, Name = "Windows Mobile", ReleaseDate = new DateTime(Convert.ToInt32(1999), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2014), 1, 1) });
            builder.HasData(new Platform() { Id = 294, Name = "Windows Phone", ReleaseDate = new DateTime(Convert.ToInt32(2010), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 295, Name = "WIPI", ReleaseDate = new DateTime(Convert.ToInt32(2005), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2008), 1, 1) });
            builder.HasData(new Platform() { Id = 296, Name = "WonderSwan", ReleaseDate = new DateTime(Convert.ToInt32(1999), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2001), 1, 1) });
            builder.HasData(new Platform() { Id = 297, Name = "WonderSwan Color", ReleaseDate = new DateTime(Convert.ToInt32(2000), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2004), 1, 1) });
            builder.HasData(new Platform() { Id = 298, Name = "XaviXPORT", ReleaseDate = new DateTime(Convert.ToInt32(2004), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2009), 1, 1) });
            builder.HasData(new Platform() { Id = 299, Name = "Xbox", ReleaseDate = new DateTime(Convert.ToInt32(2001), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2016), 1, 1) });
            builder.HasData(new Platform() { Id = 300, Name = "Xbox 360", ReleaseDate = new DateTime(Convert.ToInt32(2005), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 301, Name = "Xbox Cloud Gaming", ReleaseDate = new DateTime(Convert.ToInt32(2020), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 302, Name = "Xbox One", ReleaseDate = new DateTime(Convert.ToInt32(2013), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 303, Name = "Xbox Series", ReleaseDate = new DateTime(Convert.ToInt32(2016), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 304, Name = "Xerox Alto", ReleaseDate = new DateTime(Convert.ToInt32(1977), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1982), 1, 1) });
            builder.HasData(new Platform() { Id = 305, Name = "Z-machine", ReleaseDate = new DateTime(Convert.ToInt32(1995), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2020), 1, 1) });
            builder.HasData(new Platform() { Id = 306, Name = "Zeebo", ReleaseDate = new DateTime(Convert.ToInt32(2009), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2010), 1, 1) });
            builder.HasData(new Platform() { Id = 307, Name = "Zilog Z80", ReleaseDate = new DateTime(Convert.ToInt32(1976), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1981), 1, 1) });
            builder.HasData(new Platform() { Id = 308, Name = "Zilog Z8000", ReleaseDate = new DateTime(Convert.ToInt32(1983), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(1983), 1, 1) });
            builder.HasData(new Platform() { Id = 309, Name = "Zodiac", ReleaseDate = new DateTime(Convert.ToInt32(2003), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2007), 1, 1) });
            builder.HasData(new Platform() { Id = 310, Name = "Zune", ReleaseDate = new DateTime(Convert.ToInt32(2009), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2011), 1, 1) });
            builder.HasData(new Platform() { Id = 311, Name = "ZX Spectrum", ReleaseDate = new DateTime(Convert.ToInt32(1982), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });
            builder.HasData(new Platform() { Id = 312, Name = "ZX Spectrum Next", ReleaseDate = new DateTime(Convert.ToInt32(2017), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2022), 1, 1) });
            builder.HasData(new Platform() { Id = 313, Name = "ZX80", ReleaseDate = new DateTime(Convert.ToInt32(1980), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2012), 1, 1) });
            builder.HasData(new Platform() { Id = 314, Name = "ZX81", ReleaseDate = new DateTime(Convert.ToInt32(1981), 1, 1), LastGameReleased = new DateTime(Convert.ToInt32(2023), 1, 1) });

        }
    }
}
